---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logging
spec:
  version: 7.15.2
  count: 1
  elasticsearchRef:
    name: logging
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: kibana.example.com
